// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./layout/components/app-header/index.vue')['default']
    AppLeft: typeof import('./layout/components/app-left/index.vue')['default']
    AppMain: typeof import('./layout/components/app-main/index.vue')['default']
    BaseCheckbox: typeof import('./resources/components/base-form/components/base-checkbox/index.vue')['default']
    BaseColor: typeof import('./resources/components/base-form/components/base-color/index.vue')['default']
    BaseColorRange: typeof import('./resources/components/base-form/components/base-color-range/index.vue')['default']
    BaseDate: typeof import('./resources/components/base-form/components/base-date/index.vue')['default']
    BaseEditor: typeof import('./resources/components/base-form/components/base-editor/index.vue')['default']
    BaseForm: typeof import('./resources/components/base-form/index.vue')['default']
    BaseInput: typeof import('./resources/components/base-form/components/base-input/index.vue')['default']
    BaseInputNumber: typeof import('./resources/components/base-form/components/base-input-number/index.vue')['default']
    BaseRadio: typeof import('./resources/components/base-form/components/base-radio/index.vue')['default']
    BaseSelect: typeof import('./resources/components/base-form/components/base-select/index.vue')['default']
    BaseShowBox: typeof import('./resources/components/base-form/components/base-show-box/index.vue')['default']
    BaseShowSwitch: typeof import('./resources/components/base-form/components/base-show-switch/index.vue')['default']
    BaseSvg: typeof import('./resources/components/base-svg/index.vue')['default']
    BaseSwitch: typeof import('./resources/components/base-form/components/base-switch/index.vue')['default']
    BaseTable: typeof import('./resources/components/base-table/index.vue')['default']
    BaseTabs: typeof import('./resources/components/base-tabs/index.vue')['default']
    BaseUpload: typeof import('./resources/components/base-form/components/base-upload/index.vue')['default']
    FrameView: typeof import('./layout/components/frame-view/index.vue')['default']
    Main: typeof import('./layout/main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCol: typeof import('naive-ui')['NCol']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NRow: typeof import('naive-ui')['NRow']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./layout/index.vue')['default']
  }
}
